//A java project that allows user to Guess Number Generated by the Computer

/**********************************************
*Programmer              	: Sakshi Baglane
*Program name           	: GuessNumberGame.java
*Task Number                : 02
************************************************/

import java.util.*;

class GuessNumber0
{
    // Adding a method to determine the guessed number(userNumber) with secret
    // number

    public String determineNumber(int guessNumber, int userNumber, int count) 
    {
        if (guessNumber < 0 || guessNumber > 100) 
        {
            return "\nOops!!! Wrong Guess";
        } 
        else if (guessNumber == userNumber) 
        {
            return "\n Correct Guess!! You won \t Total Guesses: " + count;
        } 
        else if (guessNumber < userNumber) 
        {
            return "\n Your guess is too Low, try again.\t Try number: " + count;
        } 
        else if (guessNumber > userNumber) 
        {
            return "\n Your guess is too High, try again.\t Try number: " + count;
        } 
        else 
        {
            return "\n Your guess is incorrect.\nTry number: " + count;
        }
    }
}

public class GuessNumberGame 
{
    public static void main(String... args) 
    {
        Scanner sc = new Scanner(System.in);
        int userNumber = (int) (Math.random() * 100) + 1; // random number from 1 to 100
        int guessNumber = 0;
        GuessNumber g1 = new GuessNumber();
        int count = 1;
        while (guessNumber != userNumber) 
        {
            System.out.println("-------------------------------------------");
            System.out.println("\nEnter your guess between 1 and 100: \n");
            System.out.println("-------------------------------------------");
            guessNumber = sc.nextInt();
            String result = g1.determineNumber(guessNumber, userNumber, count);
            System.out.println(result);
            count++;
        }
    }
}
